export const categorySuggessions = [
  { id: "tech", text: "Technology" },
  { id: "fin", text: "Finance" },
  { id: "digimark", text: "Digital Marketing" },
  { id: "coding", text: "Programming" },
  { id: "tutorial", text: "Tutorial" },
  { id: "howto", text: "How To" },
  { id: "writing", text: "Writing" },
  { id: "inspire", text: "Inspirational" },
  { id: "science", text: "Science" },
  { id: "politics", text: "Politics" },
  { id: "lifestyle", text: "Lifestyle" },
  { id: "food", text: "Food" },
  { id: "bussiness", text: "Bussiness" },
  { id: "entrepreneur", text: "Entrepreneurs" },
  { id: "history", text: "History" },
  { id: "health", text: "Health" },
  { id: "pet", text: "Pets" },
  { id: "parenthood", text: "Parenthood" },
  { id: "travel", text: "Travel" },
  { id: "india", text: "India" },
  { id: "china", text: "China" },
  { id: "uk", text: "United Kingdom" },
  { id: "us", text: "United States" },
  { id: "world", text: "World" },
  { id: "news", text: "News" },
  { id: "review", text: "Product Review" }
]